version: "3.2"

# Project network
networks:
  project:
    name: "${PROJECT_NETWORK_NAME:-${PROJECT_NAME}}"
    external: ${PROJECT_NETWORK_EXTERNAL:-false}

# Project volumes
volumes:
  db_data: {}
  laravel-root:
    name: "${PROJECT_NAME}_root"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './'

services:

  php:
    image: wodby/php:${PHP_TAG}
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      # PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      ## Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
      # PHP_XDEBUG_MODE: debug
      # PHP_XDEBUG_MODE: profile
      # PHP_XDEBUG_USE_COMPRESSION: false
      # PHP_IDE_CONFIG: serverName=${PROJECT_BASE_URL}
      # PHP_XDEBUG_IDEKEY: "my-ide"
      LC_ALL: C
    networks:
      - project
    volumes:
      - laravel-root:/var/www/html:cached

  nginx:
    image: wodby/nginx:${NGINX_TAG}
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: "${PROJECT_NAME}_php"
      NGINX_VHOST_PRESET: php
      NGINX_SERVER_ROOT: /var/www/html/public
    networks:
      - project
    ports:
      - "${WEBSERVER_HOST_PORT:-8000}:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.services.${PROJECT_NAME}_nginx.loadbalancer.server.port=80"
    volumes:
      - laravel-root:/var/www/html:cached
